theme = "kanagawa"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"
soft-wrap = { enable = true }

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "error"

[editor.indent-guides]
render = false
character = "╎"
skip-levels = 1

[keys.insert.j]
j = "normal_mode"

[keys.normal."space"]
o = "add_newline_below"
O = "add_newline_above"
W = ":write"

[keys.normal."\\"."t"]
w = ":toggle soft-wrap.enable"
g = ":toggle indent-guides.render"
z = ":toggle gutters.line-numbers.min-width 48 3"
