#!/usr/bin/env zsh

branches=$(git branch -vv --no-color | grep ': gone]' | awk '{print $1}')

if [[ $branches == '' ]]; then
    echo "No dangling branches found"
    exit 0;
fi

echo -e "The following branches will be deleted: \n$branches\n"

read -r -p "Are you sure you want to delete? (y/N)" confirmation

if [[ $confirmation == "y" ]]; then
    for branch in $branches
    do
        git branch -D "$branch"
    done
else
    exit 0
fi

